version: '3.8'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: test-nginx
    ports:
      - '8080:8080'
    volumes:
      - ./dockerfiles/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - php
      - db

  php:
    container_name: test-php
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./:/srv/app
    links:
      - db
    restart: always

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: test-pma
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: test-db
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    restart: always

volumes:
  db: